### ISSUE TITLE
 website selection screen problem

### ISSUE THREAD

**Issue by ferhatyesilmen** [WarManX/Iphone-Reserver#3]
Does't continue to the second screen, website can't be selected.

**Comment by WarManX** [comment]
Can you please show screenshot?

**Comment by huzi132** [comment]
![image](https://user-images.githubusercontent.com/116069092/196386190-24a5005e-3da7-4830-9220-cac7ab932e1d.png)

when you click apple, it doesnt go any further, it just gets stuck

**Comment by WarManX** [comment]
Sorry I didn't check for windows. Let me check it.

**Comment by huzi132** [comment]
no problem, keep me posted :)

**Comment by huzi132** [comment]
any update?

**Comment by WarManX** [comment]
Not yet, sorry

**Comment by WarManX** [comment]
At the moment you can download v1

**Comment by WarManX** [comment]
I think the best solution for Windows is to use https://github.com/WarManX/Iphone-Reserver/releases/tag/1.0 
I did try it and worked with no issues

**Comment by amirkhonov** [comment]
I have an error with the v1 tag.
```
PS C:\Users\desktop\Downloads\Iphone.Reserver\Iphone Reserver> python .\iphone_reserver.py
Traceback (most recent call last):
  File ".\iphone_reserver.py", line 14, in <module>
    from pync import Notifier
  File "C:\Users\desktop\AppData\Local\Programs\Python\Python38\lib\site-packages\pync\__init__.py", line 3, in <module>
    from .TerminalNotifier import Notifier, notify
  File "C:\Users\desktop\AppData\Local\Programs\Python\Python38\lib\site-packages\pync\TerminalNotifier.py", line 137, in <module>
    Notifier = TerminalNotifier()
  File "C:\Users\desktop\AppData\Local\Programs\Python\Python38\lib\site-packages\pync\TerminalNotifier.py", line 23, in __init__
    proc = subprocess.Popen(["which", "terminal-notifier"], stdout=subprocess.PIPE)
  File "C:\Users\desktop\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\desktop\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by WarManX** [comment]
These lines just comment them or remove them

14
210

Because notifier is not working with Windows

**Comment by WarManX** [comment]
These lines just comment them or remove them

14
210

Because notifier is not working with Windows

**Comment by amirkhonov** [comment]
Sorry for the offtop. Do you know guys how to bypass SMS request? The service is requesting the SMS code while ordering.

**Comment by WarManX** [comment]
> Sorry for the offtop. Do you know guys how to bypass SMS request? The service is requesting the SMS code while ordering.

No sorry, did think about it before

**Comment by WarManX** [comment]
> I have an error with the v1 tag.
> 
> ```
> 
> PS C:\Users\desktop\Downloads\Iphone.Reserver\Iphone Reserver> python .\iphone_reserver.py
> 
> Traceback (most recent call last):
> 
>   File ".\iphone_reserver.py", line 14, in <module>
> 
>     from pync import Notifier
> 
>   File "C:\Users\desktop\AppData\Local\Programs\Python\Python38\lib\site-packages\pync\__init__.py", line 3, in <module>
> 
>     from .TerminalNotifier import Notifier, notify
> 
>   File "C:\Users\desktop\AppData\Local\Programs\Python\Python38\lib\site-packages\pync\TerminalNotifier.py", line 137, in <module>
> 
>     Notifier = TerminalNotifier()
> 
>   File "C:\Users\desktop\AppData\Local\Programs\Python\Python38\lib\site-packages\pync\TerminalNotifier.py", line 23, in __init__
> 
>     proc = subprocess.Popen(["which", "terminal-notifier"], stdout=subprocess.PIPE)
> 
>   File "C:\Users\desktop\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 858, in __init__
> 
>     self._execute_child(args, executable, preexec_fn, close_fds,
> 
>   File "C:\Users\desktop\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1311, in _execute_child
> 
>     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
> 
> FileNotFoundError: [WinError 2] The system cannot find the file specified
> 
> ```

These lines just comment them or remove them

14
210

Because notifier is not working with Windows

**Comment by amirkhonov** [comment]
> These lines just comment them or remove them
> 
> 14 210
> 
> Because notifier is not working with Windows

Thank you! It is working now.

**Comment by WarManX** [comment]
Let me know guys if everything works fine

**Comment by huzi132** [comment]
![image](https://user-images.githubusercontent.com/116069092/196468728-d1e8974b-68a0-4849-8c12-9302feb453f9.png)

this is the error im getting in v1
