### ISSUE TITLE
![image](https://user-images.githubusercontent.com/116069092/196468728-d1e8974b-68a0-4849-8c12-9302feb453f9.png)

### ISSUE THREAD

**Issue by huzi132** [WarManX/Iphone-Reserver#4]
![image](https://user-images.githubusercontent.com/116069092/196468728-d1e8974b-68a0-4849-8c12-9302feb453f9.png)

this is the error im getting in v1

_Originally posted by @huzi132 in https://github.com/WarManX/Iphone-Reserver/issues/3#issuecomment-1282543453_

**Comment by huzi132** [comment]
any idea how to fix it?

**Comment by WarManX** [comment]
You can use 

```
pip install chime
```

Or 

```
pip3 install chime
```

**Comment by WarManX** [comment]
It's better to keep your phone beside you when trying to reserve iPhone because it's faster

Whenever the tool find iPhone quickly reserve it with your phone

**Comment by huzi132** [comment]
thanks
